/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1individual;

import java.awt.Image;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author arman
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    Imagen img = new Imagen();
    int x_init;
    int y_init;
    int x_end;
    int y_end;
    
    public UI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Op16 = new javax.swing.JLabel();
        Op15 = new javax.swing.JLabel();
        Op14 = new javax.swing.JLabel();
        Op13 = new javax.swing.JLabel();
        Op12 = new javax.swing.JLabel();
        Op11 = new javax.swing.JLabel();
        Op10 = new javax.swing.JLabel();
        Op9 = new javax.swing.JLabel();
        Op8 = new javax.swing.JLabel();
        Op7 = new javax.swing.JLabel();
        Op6 = new javax.swing.JLabel();
        Op5 = new javax.swing.JLabel();
        Op4 = new javax.swing.JLabel();
        Op3 = new javax.swing.JLabel();
        Op2 = new javax.swing.JLabel();
        Op1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Op16.setBackground(new java.awt.Color(0, 0, 0));
        Op16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Op16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpcionesIMG(evt);
            }
        });
        getContentPane().add(Op16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 100, 100));
        Op16.getAccessibleContext().setAccessibleName("Op16");

        Op15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Op15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpcionesIMG(evt);
            }
        });
        getContentPane().add(Op15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 100, 100));
        Op15.getAccessibleContext().setAccessibleName("Op15");

        Op14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Op14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpcionesIMG(evt);
            }
        });
        getContentPane().add(Op14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 100, 100));
        Op14.getAccessibleContext().setAccessibleName("Op14");

        Op13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Op13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpcionesIMG(evt);
            }
        });
        getContentPane().add(Op13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 100, 100));
        Op13.getAccessibleContext().setAccessibleName("Op13");

        Op12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Op12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpcionesIMG(evt);
            }
        });
        getContentPane().add(Op12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 100, 100));
        Op12.getAccessibleContext().setAccessibleName("Op12");

        Op11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Op11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpcionesIMG(evt);
            }
        });
        getContentPane().add(Op11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 100, 100));
        Op11.getAccessibleContext().setAccessibleName("Op11");

        Op10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Op10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpcionesIMG(evt);
            }
        });
        getContentPane().add(Op10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 100, 100));
        Op10.getAccessibleContext().setAccessibleName("Op10");

        Op9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Op9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpcionesIMG(evt);
            }
        });
        getContentPane().add(Op9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 100, 100));
        Op9.getAccessibleContext().setAccessibleName("Op9");

        Op8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Op8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpcionesIMG(evt);
            }
        });
        getContentPane().add(Op8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 100, 100));
        Op8.getAccessibleContext().setAccessibleName("Op8");

        Op7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Op7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpcionesIMG(evt);
            }
        });
        getContentPane().add(Op7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 100, 100));
        Op7.getAccessibleContext().setAccessibleName("Op7");

        Op6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Op6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpcionesIMG(evt);
            }
        });
        getContentPane().add(Op6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 100, 100));
        Op6.getAccessibleContext().setAccessibleName("Op6");

        Op5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Op5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpcionesIMG(evt);
            }
        });
        getContentPane().add(Op5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 100, 100));
        Op5.getAccessibleContext().setAccessibleName("Op5");

        Op4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Op4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpcionesIMG(evt);
            }
        });
        getContentPane().add(Op4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 100, 100));
        Op4.getAccessibleContext().setAccessibleName("Op4");

        Op3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Op3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpcionesIMG(evt);
            }
        });
        getContentPane().add(Op3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 100, 100));
        Op3.getAccessibleContext().setAccessibleName("Op3");

        Op2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Op2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpcionesIMG(evt);
            }
        });
        getContentPane().add(Op2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 100, 100));
        Op2.getAccessibleContext().setAccessibleName("Op2");

        Op1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Op1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Op1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Op1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpcionesIMG(evt);
            }
        });
        getContentPane().add(Op1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 100, 100));
        Op1.getAccessibleContext().setAccessibleName("Op1");

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Zoom");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 620, 110, 40));
        jButton2.getAccessibleContext().setAccessibleName("Zoom");

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, 110, 40));

        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 400, 400));
        jLabel4.getAccessibleContext().setAccessibleName("FotoZoom");

        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 400, 400));
        jLabel2.getAccessibleContext().setAccessibleName("ImagenCargar");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1individual/Imagenes/FondoOpcion2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jLabel1.getAccessibleContext().setAccessibleName("fondo");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    File imagen;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        int resultado;
        
        BuscarIMG Buscador = new BuscarIMG();
        
        FileNameExtensionFilter formato = new FileNameExtensionFilter("JPG, PNG","jpg","png");
        
        Buscador.jFileChooser1.setFileFilter(formato);
        
        resultado = Buscador.jFileChooser1.showOpenDialog(null);
        
        if (JFileChooser.APPROVE_OPTION == resultado){  
            imagen = Buscador.jFileChooser1.getSelectedFile();
            
            try{ 
                ImageIcon ImgIcon = new ImageIcon(imagen.toString());
                Icon icono = new ImageIcon(ImgIcon.getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_DEFAULT));
                jLabel2.setIcon(icono);
                
                
                
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, "Error al abrir");
            }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    JLabel JlabelAntiguo;
    private void OpcionesIMG(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpcionesIMG
                
        
        if(imagen!=null){
            jButton2.setEnabled(true);
            JLabel item = (JLabel) evt.getSource();
            item.setHorizontalAlignment(JLabel.CENTER);
            ImageIcon ImgIcon = new ImageIcon(getClass().getResource("/proyecto1individual/Imagenes/correct.png"));
            Icon icono = new ImageIcon(ImgIcon.getImage().getScaledInstance(ImgIcon.getIconWidth(), ImgIcon.getIconHeight(), Image.SCALE_DEFAULT));

            if(JlabelAntiguo!=null){
                JlabelAntiguo.setIcon(null);
            }
            item.setIcon(icono);
            JlabelAntiguo = (JLabel) evt.getSource();
            CambiarSeleccion(item.getAccessibleContext().getAccessibleName());
        }
    }//GEN-LAST:event_OpcionesIMG

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            img.pixelesImagen(imagen.getAbsolutePath(), x_init, y_init, x_end, y_end);

    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void CambiarSeleccion(String Selector){
        if(Selector.equals("Op1")){
            x_init=0;
            y_init=0;
            x_end=100;
            y_end=100;
        }else if(Selector.equals("Op2")){
            x_init=100;
            y_init=0;
            x_end=200;
            y_end=100;
        }else if(Selector.equals("Op3")){
            x_init=200;
            y_init=0;
            x_end=300;
            y_end=100;
        }else if(Selector.equals("Op4")){
            x_init=300;
            y_init=0;
            x_end=400;
            y_end=100;
        }else if(Selector.equals("Op5")){
            x_init=0;
            y_init=100;
            x_end=100;
            y_end=200;
        }else if(Selector.equals("Op6")){
            x_init=100;
            y_init=100;
            x_end=200;
            y_end=200;
        }else if(Selector.equals("Op7")){
            x_init=200;
            y_init=100;
            x_end=300;
            y_end=200;
        }else if(Selector.equals("Op8")){
            x_init=300;
            y_init=100;
            x_end=400;
            y_end=200;
        }else if(Selector.equals("Op9")){
            x_init=0;
            y_init=200;
            x_end=100;
            y_end=300;
        }else if(Selector.equals("Op10")){
            x_init=100;
            y_init=200;
            x_end=200;
            y_end=300;
        }else if(Selector.equals("Op11")){
            x_init=200;
            y_init=200;
            x_end=300;
            y_end=300;
        }else if(Selector.equals("Op12")){
            x_init=300;
            y_init=200;
            x_end=400;
            y_end=300;
        }else if(Selector.equals("Op12")){
            x_init=300;
            y_init=200;
            x_end=400;
            y_end=300;
        }else if(Selector.equals("Op13")){
            x_init=0;
            y_init=300;
            x_end=100;
            y_end=400;
        }else if(Selector.equals("Op14")){
            x_init=100;
            y_init=300;
            x_end=200;
            y_end=400;
        }else if(Selector.equals("Op15")){
            x_init=200;
            y_init=300;
            x_end=300;
            y_end=400;
        }else if(Selector.equals("Op16")){
            x_init=300;
            y_init=300;
            x_end=400;
            y_end=400;
        }
        
       
    }
            
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Op1;
    private javax.swing.JLabel Op10;
    private javax.swing.JLabel Op11;
    private javax.swing.JLabel Op12;
    private javax.swing.JLabel Op13;
    private javax.swing.JLabel Op14;
    private javax.swing.JLabel Op15;
    private javax.swing.JLabel Op16;
    private javax.swing.JLabel Op2;
    private javax.swing.JLabel Op3;
    private javax.swing.JLabel Op4;
    private javax.swing.JLabel Op5;
    private javax.swing.JLabel Op6;
    private javax.swing.JLabel Op7;
    private javax.swing.JLabel Op8;
    private javax.swing.JLabel Op9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
